//let mydate=new Date()
//console.log(Date)
//console.log(mydate.toString())
//console.log(mydate.toJSON())
//console.log(mydate.toDateString())
//console.log(mydate.toTimeString())
let updatedDate=new Date(2023,0,23)
console.log(updatedDate)